# 📊 Logistic Regression (Binary Classification)

## Introduction

Machine Learning problems are broadly divided into two categories:

1. **Regression** – Predicts continuous numerical values.
2. **Classification** – Predicts categorical labels or classes.

Logistic Regression is one of the most popular **Supervised Machine Learning Classification algorithms**.

Despite its name containing the word **Regression**, Logistic Regression is actually used for **Classification Problems** because it predicts the **probability** of an observation belonging to a particular class.

For example:

- Email → Spam or Not Spam
- Student → Pass or Fail
- Customer → Buy or Not Buy
- Patient → Disease or No Disease

Unlike Linear Regression, which predicts continuous values, Logistic Regression predicts values between **0 and 1**, representing probabilities.

The predicted probability is then converted into a class label using a threshold (usually **0.5**).

---

## Why Logistic Regression?

Suppose we want to predict whether a student will pass an exam.

Linear Regression may predict values like:

- 1.25
- -0.42
- 2.10

These predictions are not valid probabilities because probabilities must always lie between **0 and 1**.

Logistic Regression solves this problem by using the **Sigmoid Function**, which converts any real number into a probability between **0 and 1**.

---

## Applications

Logistic Regression is widely used in:

- Spam Email Detection
- Disease Prediction
- Loan Approval
- Credit Card Fraud Detection
- Customer Churn Prediction
- Sentiment Analysis
- Employee Attrition Prediction
- Marketing Campaign Prediction

---

## Goal of This Notebook

In this notebook, we will:

- Understand Classification
- Learn different Types of Classification
- Load a real dataset
- Explore the dataset
- Preprocess the data
- Train a Logistic Regression model
- Make predictions
- Evaluate model performance
- Understand Evaluation Metrics
- Interpret the results

# Step 1: Import Required Libraries

Before building any Machine Learning model, we need to import the required Python libraries.

Libraries used in this notebook:

- pandas → Reading and manipulating data
- numpy → Numerical computations
- matplotlib → Data visualization
- seaborn → Statistical visualization
- sklearn → Machine Learning algorithms and evaluation metrics

In [19]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

# Step 2: Load the Dataset

We load the Social Network Ads dataset using pandas.

The dataset contains customer information such as:

- Gender
- Age
- Estimated Salary

Our objective is to predict whether the customer purchases the product.

In [20]:
df = pd.read_csv("Social_Network_Ads.csv")

df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

# Step 3: Explore the Dataset

Before training any Machine Learning model, it is important to understand the dataset.

We use:

- head() → Displays first five rows
- shape → Number of rows and columns
- info() → Data types and missing values
- describe() → Statistical summary

This helps us identify:

- Missing values
- Data types
- Feature distribution
- Dataset size

In [21]:
print(df.head())

print()

print(df.shape)

print()

df.info()

print()

df.describe()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

(400, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

# Step 4: Checking Missing Values

Machine Learning models cannot work with missing values.

We verify whether the dataset contains any missing data.

In [23]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

# Step 5: Understanding the Features

Our dataset contains five columns.

| Feature | Description |
|----------|-------------|
| User ID | Unique customer ID |
| Gender | Male or Female |
| Age | Customer Age |
| EstimatedSalary | Annual Salary |
| Purchased | Target Variable |

Notice that **User ID** is simply an identifier.

It does not help the model learn any purchasing pattern.

Therefore, we remove it.

In [24]:
df = df.drop("User ID", axis=1)

df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

# Step 6: Encoding Categorical Data

Machine Learning algorithms work only with numbers.

The Gender column contains text values.

Male

Female

We convert them into numbers using Label Encoding.

Example

Male → 1

Female → 0

In [25]:
encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

# Step 7: Defining Features and Target

Machine Learning datasets are divided into:

X → Independent Variables (Features)

y → Dependent Variable (Target)

Features:

- Gender
- Age
- EstimatedSalary

Target:

Purchased

In [34]:


X = df.drop("Purchased", axis=1)

y = df["Purchased"]

# Step 8: Splitting the Dataset

We split the dataset into:

Training Data → 80%

Testing Data → 20%

The model learns from the training data and is evaluated on the testing data.

This helps us measure how well the model performs on unseen data.

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Step 9: Feature Scaling

Logistic Regression performs better when numerical features are on a similar scale.

Example

Age = 20

Salary = 90000

Since Salary has much larger values, it may dominate the learning process.

StandardScaler transforms both features to have similar scales.

This improves model convergence and performance.

In [36]:

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

# Step 10: Creating the Logistic Regression Model

Now we create the Logistic Regression model.

Initially, the model does not know any relationship between the features and the target.

It will learn this relationship during training.

In [37]:
model = LogisticRegression(random_state=42)

# Step 11: Training the Model

Training means teaching the model using historical data.

During training, Logistic Regression:

1. Initializes random weights
2. Calculates probabilities
3. Computes Log Loss
4. Updates weights
5. Repeats until convergence

The learned weights are stored inside the model.

In [38]:
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

# Step 12: Making Predictions

After training, we use the testing dataset to predict whether customers purchase the product.

The model returns either:

0 → Not Purchased

1 → Purchased

In [39]:
y_pred = model.predict(X_test)

y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

# Step 13: Predicting Probabilities

Instead of directly predicting classes, Logistic Regression first predicts probabilities.

For example:

[0.92 0.08]

means

92% probability of class 0

8% probability of class 1

The class with the higher probability becomes the prediction.

In [40]:
probabilities = model.predict_proba(X_test)

print(probabilities[:5])

[[0.8794539  0.1205461 ]
 [0.84736193 0.15263807]
 [0.79223505 0.20776495]
 [0.91943034 0.08056966]
 [0.91186646 0.08813354]]

# Evaluation Metrics for Classification

Unlike Regression problems, Classification models cannot be evaluated using metrics such as Mean Squared Error (MSE) alone.

Instead, we use specialized Classification Metrics.

The most commonly used metrics are:

- Accuracy
- Confusion Matrix
- Precision
- Recall
- F1 Score
- ROC Curve
- AUC Score

Each metric provides different information about model performance.

Choosing the correct evaluation metric depends on the problem being solved.

# Accuracy

Accuracy measures the overall correctness of the model.

It is the ratio of correctly predicted observations to the total observations.

Formula

Accuracy = (TP + TN) / (TP + TN + FP + FN)

Where

TP = True Positive

TN = True Negative

FP = False Positive

FN = False Negative

Example

Suppose:

Correct Predictions = 95

Total Predictions = 100

Accuracy = 95 / 100

Accuracy = 95%

Higher Accuracy generally indicates better model performance.

However, Accuracy may be misleading for imbalanced datasets.

# Confusion Matrix

A Confusion Matrix summarizes the performance of a Classification model.

It consists of four values.

|                | Predicted Positive | Predicted Negative |
|----------------|-------------------|-------------------|
| Actual Positive | True Positive (TP) | False Negative (FN) |
| Actual Negative | False Positive (FP) | True Negative (TN) |

Meaning of each term

True Positive (TP)

The model correctly predicts the positive class.

Example:

Patient has cancer

Model predicts cancer

True Negative (TN)

The model correctly predicts the negative class.

Example:

Patient is healthy

Model predicts healthy

False Positive (FP)

The model predicts positive but the actual class is negative.

Example:

Healthy patient predicted as cancer.

False Negative (FN)

The model predicts negative but the actual class is positive.

Example:

Cancer patient predicted as healthy.

False Negatives are usually more dangerous in medical applications.

# Precision

Precision answers the question:

"Out of all positive predictions, how many were actually positive?"

Formula

Precision = TP / (TP + FP)

High Precision means the model makes very few False Positive predictions.

Example Applications

- Spam Detection
- Email Filtering
- Search Engines

# Recall (Sensitivity)

Recall answers the question:

"Out of all actual positive cases, how many did the model correctly identify?"

Formula

Recall = TP / (TP + FN)

High Recall means very few False Negatives.

Recall is extremely important in:

- Disease Prediction
- Fraud Detection
- Security Systems

# F1 Score

F1 Score is the harmonic mean of Precision and Recall.

Formula

F1 = 2 × (Precision × Recall) / (Precision + Recall)

F1 Score becomes useful when:

- Dataset is imbalanced
- Both Precision and Recall are equally important

Range

0 → Worst

1 → Best

# ROC Curve and AUC Score

ROC stands for

Receiver Operating Characteristic Curve.

It compares

True Positive Rate (Recall)

against

False Positive Rate

at different classification thresholds.

The Area Under the ROC Curve (AUC) summarizes the model's ability to distinguish between positive and negative classes.

Interpretation

AUC = 1.0 → Perfect Classifier

AUC = 0.90 → Excellent

AUC = 0.80 → Good

AUC = 0.50 → Random Guessing

Higher AUC indicates a better classification model.

# Step 14: Model Evaluation

We evaluate the model using:

- Accuracy
- Confusion Matrix
- Classification Report
- ROC-AUC Score

These metrics tell us how well the model performs on unseen data.

In [41]:
print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nROC-AUC :", roc_auc_score(y_test, model.predict_proba(X_test)[:,1]))

Accuracy : 0.9

Confusion Matrix
[[65  3]
 [ 7 25]]

Classification Report
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        68
           1       0.89      0.78      0.83        32

    accuracy                           0.90       100
   macro avg       0.90      0.87      0.88       100
weighted avg       0.90      0.90      0.90       100


ROC-AUC : 0.9549632352941175

# Conclusion

In this notebook, we successfully built a **Logistic Regression** model to predict whether a customer would purchase a product based on features such as **Gender, Age, and Estimated Salary**.

We began by understanding the dataset, exploring its structure, checking for missing values, and preprocessing the data by removing unnecessary columns and encoding categorical variables. We then split the dataset into training and testing sets and applied **StandardScaler** to normalize the feature values, improving the performance of the Logistic Regression model.

After training the model, we made predictions on the test dataset and evaluated its performance using several classification metrics, including:

- **Accuracy**
- **Confusion Matrix**
- **Precision**
- **Recall**
- **F1-Score**
- **ROC-AUC Score**

These metrics provided a comprehensive understanding of the model's performance beyond overall accuracy.

### Key Takeaways

- Logistic Regression is a **Supervised Machine Learning Classification Algorithm** primarily used for **Binary Classification** problems.
- It predicts the **probability** of an observation belonging to a particular class using the **Sigmoid Function**.
- Feature scaling significantly improves the model's performance and convergence.
- Evaluation metrics such as Precision, Recall, F1-Score, and ROC-AUC are essential for assessing classification models, especially when dealing with imbalanced datasets.
- Logistic Regression is simple, interpretable, computationally efficient, and serves as an excellent baseline model for many real-world classification tasks.

### Final Outcome

The trained Logistic Regression model successfully learned the relationship between customer characteristics and purchasing behavior, enabling it to predict whether a customer is likely to purchase a product. This demonstrates how Logistic Regression can be effectively applied to solve real-world binary classification problems in domains such as marketing, healthcare, finance, fraud detection, and customer analytics.